### ISSUE TITLE
Update broken Social Media links

### ISSUE THREAD

**Issue by cynamonster** [FSUInnovationHub/InnovationHubWebsite#15] opened 2018-10-29 17:43 UTC
Now that we've changed the Hub's social media tags from 'FSUInnovates' to 'fsuinnovationhub', the CONNECT WITH US links within `<section id="about">` and `<footer>` are broken

**Comment by glfmn** [comment] 2018-11-07 23:33
Duplicate of #12 

The changes have been made but we have to find an easy way to push our changes to the live site.

**Closed by glfmn** 2018-11-07 23:33 UTC
Labels: duplicate
